### ISSUE TITLE
I get the following error Uncaught TypeError: Cannot read property 'getState' of undefined on chrome browser

### ISSUE THREAD

**Issue by ftschris** [Tracardi/tracardi-gui#1]
Uncaught TypeError: Cannot read property 'getState' of undefined
    at i ((index):65)
    at HTMLScriptElement.<anonymous> ((index):65)

**Comment by ftschris** [comment]
Also when using on https website

(index):136 Mixed Content: The page at 'https://intelbuildpro.com/' was loaded over HTTPS, but requested an insecure script 'http://63.250.53.197:8787/tracker/tracker.min.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by atompie** [comment]
@ftschris Thank you for reporting this issue. Currently Tracardi does not support https. Nevertheless I try to fix this and get back to you. 
Do you use docker version of tracardi?

**Comment by atompie** [comment]
> Uncaught TypeError: Cannot read property 'getState' of undefined
> at i ((index):65)
> at HTMLScriptElement. ((index):65)

As for this error. You probably configured location of tracker script. It is on the same server as api. 

```javascript
const options = {
        tracker: {
            url: {
                script: 'http://63.250.53.197:8787/tracker',  // <- here is the error, wrong port. 
                api: 'http://63.250.53.197:8686'
            },
            source: {
                id: "e39017b2-4cc5-4e19-afa3-a01f88f4a615"
            }
        }
    }
```

Change `http://63.250.53.197:8787/tracker` to `http://63.250.53.197:8686/tracker`

**Comment by atompie** [comment]
If you type `http://63.250.53.197:8787/tracker/tracker.min.js` into browser you will not get js file.

**Comment by ftschris** [comment]
Hi.
Tnx for the info.
Also i get this 

DevTools failed to load source map: Could not load content for http://63.250.53.197:8686/tracker/loader.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by ftschris** [comment]
Also look at this pls.
Access to XMLHttpRequest at 'http://63.250.53.197:8686/track' from origin 'http://sparktechnologies.eu' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

**Comment by atompie** [comment]
> Hi.
> Tnx for the info.
> Also i get this
> 
> DevTools failed to load source map: Could not load content for http://63.250.53.197:8686/tracker/loader.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

This is is fixed in upcoming release. Does not make an impact on tracardi.

**Comment by atompie** [comment]
> Hi.
> Tnx for the info.
> Also i get this
> 
> DevTools failed to load source map: Could not load content for http://63.250.53.197:8686/tracker/loader.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

This one is connected with some error that is raised on server side. Are able to paste here log form docker of tracardi api?
You probably cloned some of the version with error on api side. If you could paste that error that will shed some light on error.

**Comment by atompie** [comment]
This is solved with https docker for gui.
