### ISSUE TITLE
Make JSON FORM field with available frields from event index

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi-gui#139]
# Task

Make JSO FORM field with available event index fields. Needed for event aggregator

## Example 
![Screenshot from 2022-06-11 14-24-11](https://user-images.githubusercontent.com/16271564/173187842-7140d67b-35a1-4964-8631-03c1ca26b7c2.png)
.

**Comment by DawidekZagajnik** [comment]
it was already there! just a matter of using already present features

**Comment by atompie** [comment]
@DawidekZagajnik When the plugin is being run we get the following error:

```
SerializationError: ({'size': 0, 'query': {'bool': {'must': [{'range': {'metadata.time.insert': {'gte': 'now-900s', 'lte': 'now'}}}, {'term': {'profile.id': '@debug-profile-id'}}]}}, 'aggs': {'events_bucket': {'terms': {'field': NamedEntity(id='profile.id', name='profile.id'), 'size': 15}}}}, 
```

It seems that the events bucket gets the NamedEntity.

**Comment by DawidekZagajnik** [comment]
@atompie there should be also a PR for Tracardi, config structure needed to be changed for the bug not to occur

**Comment by atompie** [comment]
@DawidekZagajnik I have merged all the have been. Or maybe I am missing something. This is what has left in PR queue.

![Screenshot from 2022-08-01 22-30-27](https://user-images.githubusercontent.com/16271564/182241747-31609c84-fe89-4e8a-91e8-8d9e3a69117c.png)

**Comment by atompie** [comment]
@DawidekZagajnik is it this #618? It was not connected with tracardi-gui#139 I was closing.

**Comment by DawidekZagajnik** [comment]
@atompie seems like it is

**Comment by atompie** [comment]
@DawidekZagajnik I have merged it it is not the one. It has to do with ES query.  That by the way also fails.
![Screenshot from 2022-08-01 22-48-16](https://user-images.githubusercontent.com/16271564/182244130-62dc7503-72e3-4a30-9054-119d5c3a1104.png)

**Comment by DawidekZagajnik** [comment]
Okay I'm gonna check on it
