### ISSUE TITLE
Add delete RULE to rule drawer in workflow

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi-gui#182]
This window is missing delete functionality. Deletion should be confirmed by modal window confirmation window. 

![Screenshot from 2022-07-12 14-05-45](https://user-images.githubusercontent.com/16271564/178486238-788757da-ffb8-4743-adb2-f53c3db9b05f.png)

**Comment by DawidekZagajnik** [comment]
merged, seems like it goes to 0.7.1
