### ISSUE TITLE
Componet that count days passed form given date

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi-gui#235]
Given the data e.g.: 2022-10-12 08:29:57 create a component that will display how many days passed from the given date.

```
<DaysPassed date={"2022-10-12 08:29:57"}/>
```

returns - 2days 20 min. It should also work for future dates too.

**Comment by chaaals** [comment]
hey @atompie , can I work on this one?

**Comment by atompie** [comment]
@chaaals sure
