### ISSUE TITLE
[Improve]Add active style for active menu row

### ISSUE THREAD

**Issue by ryomahan** [Tracardi/tracardi-gui#251]
use redux and react-router-dom to modify MainMenu.js so that menu row has active style, example:

![Nov-17-2022 20-47-12](https://user-images.githubusercontent.com/18721016/202450444-96173e95-04cf-4654-b5f3-9919db4189d6.gif)

**Comment by ryomahan** [comment]
@atompie If this is in your plan, I can submit a PR, otherwise just close it.

**Comment by atompie** [comment]
@ryomahan please make a PR I will take a look at this. What I see on the animation that it flickers a lot. Don't know why is that.

**Comment by ryomahan** [comment]
@atompie I submit it on #252

**Comment by ryomahan** [comment]
The git flickers because the mouse is not recorded.
