### ISSUE TITLE
Bug: /home/events page, the events detail list can't dynamic update

### ISSUE THREAD

**Issue by ryomahan** [Tracardi/tracardi-gui#57]
**route: /home/events**

**bug detail:** 
when the filter button on /home/events is clicked, the bar charts is dynamic updated, but the events' detail info list is not updated unless the page is refreshed.

**Comment by atompie** [comment]
@ryomahan Thanks for spotting this issue. This is actually a duplicate of https://github.com/Tracardi/tracardi-gui/issues/50 and we will soon make it go away. :)

**Comment by atompie** [comment]
Duplicate of #50

**Comment by atompie** [comment]
React.memo was removed and it solved the problem for this release.
