### ISSUE TITLE
Consent type form and list

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi-gui#62]
- [ ] Form that will add consents to tracardi using the enpoint https://github.com/Tracardi/tracardi/issues/204
- [ ] List of consents with the delete on every row: 
       
Endpoints:

* https://github.com/Tracardi/tracardi/issues/206
* https://github.com/Tracardi/tracardi/issues/205

## Form components:

Use Mui components

"id": <uuid>, : Hidden
"name": input,
"description": textarea,
"revokable": switch,
"default_value": select[grant|deny]

## Styling

Use TuiForm for styling:
  https://github.com/Tracardi/tracardi-gui/tree/master/src/components/elements/tui

Example:
https://github.com/Tracardi/tracardi-gui/blob/master/src/components/elements/details/ProfileDetails.js

**Comment by atompie** [comment]
@danjohnson77 Hi Daniel. Would you mind helping us with this task?

You will need an update on backend and frontend to see the new API.

Best.

**Comment by danjohnson77** [comment]
@atompie Hi Risto, hope alls well! Just getting back to my desk after traveling last week, happy to take this on! Will update all before starting, thanks!

**Comment by atompie** [comment]
@danjohnson77 thanks Daniel. Have a safe travel :)

**Comment by danjohnson77** [comment]
@atompie Just want to confirm you'd like the Consent Types listed using the Properties component, like in Profile Details? Or if not, is there an existing list component you'd like it based on? 

I've got the Add form up, if you want go ahead and clone off my fork (branch consent-type-form-and-list) and go to /tryout, let me know if the styling is what you're expecting, thanks!

**Comment by atompie** [comment]
@danjohnson77 I'd rather use something else. Could you suggest something?

**Comment by atompie** [comment]
We do not have a list component for now.

**Comment by danjohnson77** [comment]
@atompie If it's just list the title and delete, the Key Value form could work. 

For some reason when I go to npm install off the current master branch I'm getting dependency errors, seeing anything like that on your end?

**Comment by atompie** [comment]
No. We use yarn. Did you make a source update on your fork?

**Comment by atompie** [comment]
maybe you could delete package.lock

**Comment by danjohnson77** [comment]
That's why I need the second cup of coffee lol, working now thanks.

You can clone the consent-type branch on my fork and look at /tryout, let me know if that's what you're looking for in terms of the add form.

**Comment by atompie** [comment]
@danjohnson77 OK. BTW. We opened a slack channel for better communication on none issue related talks would you like to join? https://join.slack.com/t/tracardi/shared_invite/zt-znlomuhd-fatn3qxuI7VO9sBlHk~NhA

**Comment by danjohnson77** [comment]
@atompie Sounds great, just joined!
