### ISSUE TITLE
Generic table component based on react-window 

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi-gui#73]
We need a generic table component that we could use to display data. The data can be huge so using react-window is a must (https://github.com/bvaughn/react-window).

Row height will not be variant - this is the requirement for react-window. This component should auto load on scroll. 

It should be flexible enough to add new columns. It could look like this.

```
<Table data={}>
  <Column header="Name">{name}</Column>
  <Column header="Surname">{surname}</Column>
</Table>
```

Maybe the children needs to be a function like this (if react window needs this):

```
<Table data={} columns={["Name", "Surname]}>
  {(data) => (<Column header="Name">{data.name}</Column>
  <Column header="Surname">{data.surname}</Column>
  )}
</Table>
```

This is up to you how you structure the component as long as it is flexible enough to pass data and modify the display of single column.

**Comment by atompie** [comment]
@danjohnson77 I assigned this one to you as you are familiar with react-window. Let me know it it is OK with you? :)

**Comment by danjohnson77** [comment]
@atompie Yeah looks good, especially if row height can be static. Will take a look with fresh eyes in the morning and send questions but shouldn't be a problem.

**Comment by atompie** [comment]
Thanks

**Comment by Bruce-Hopkins** [comment]
I'm looking into React window now. It seems straightforward. Do we need lazy-loading too?

Can I be assigned the issue?

**Comment by atompie** [comment]
@Bruce-Hopkins Yes lazy loading would be great.

**Comment by Bruce-Hopkins** [comment]
#90 

Right now the table is a single row. Should it be multiple rows? I was also thinking about being able to pass into the props the color of the row, (right now every odd-numbered row is white and every even-numbered row is yellow.)
