### ISSUE TITLE
Widget: Question popup

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi-gui#80]
A popup window with a question and 2 answers. 

# Input

- Position vertical I horizontal: eg. top, right
- Two answers
- Event type to raise when an answer is clicked

Send query to /track endpoint.

![Jsw jsfor_ net-pop-up-ads](https://user-images.githubusercontent.com/16271564/147735907-78a03c14-7cc6-4586-bc6f-9641f38f0541.jpg)

Use material UI widgets
 

Documentation on getting started with micro frameworks. 

[http://docs.tracardi.com/development/micro_frontend/](http://docs.tracardi.com/development/micro_frontend/)

**Comment by DawidekZagajnik** [comment]
done, could you assign me and check my repo? 
https://github.com/DawidekZagajnik/tracardi-widget-question-popup
