### ISSUE TITLE
Widget: Survey widget

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi-gui#81]
# Widget with survey

# Input

Inputs should be passed to widget as data-.. atributtes

 - data-question
 - data-answers - string separated with commas
 - data-type-of-answer,  possible values: many, single
 - data-event-type to raise
 - data-button-label
 - data-position of the pop-up (e.g. top, right)
 
Send query to /track endpoint.

# Tips
- Use material UI widgets (https://mui.com/)

The widget should present the survey and depending on the answer type allow the user to select 1 or many answers. Then answers should be sent to tracardi /track endpoint. 

It is a POST endpoint - and documentation on how to send data can be found here: [http://docs.tracardi.com/events/event_tracking/](http://docs.tracardi.com/events/event_tracking/)

For the dev purposes You may need to run a docker container with Tracardi API (this is where the /track endpoint is).

More on how to install tracardi here:
http://docs.tracardi.com/installation/docker/

![Screenshot from 2021-12-30 09-47-28](https://user-images.githubusercontent.com/16271564/147736104-0a9037db-91fc-47b2-b344-5d52d81f16c1.png)

**Comment by Quado2** [comment]
Good day. I would like to work on this issue

**Comment by atompie** [comment]
@Quado2 documentation on writing micro front ends. This may be helpful [http://docs.tracardi.com/development/micro_frontend/](http://docs.tracardi.com/development/micro_frontend/)
