### ISSUE TITLE
Widget: Rating widget

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi-gui#82]
# Input

- Message
- Position

------

* Use material UI
* Use repo `https://github.com/Tracardi/tracardi-uix-template` as a template

------

![Screenshot from 2021-12-30 10-28-44](https://user-images.githubusercontent.com/16271564/147739195-403f93a9-0238-4d5f-bb4b-7da5fcb48bea.png)

**Comment by DawidekZagajnik** [comment]
I can try to take care of this one

**Comment by DawidekZagajnik** [comment]
done
